'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const faults=[
{title:'A connection changed during assembly',why:'A loose terminal, wrong connector pin, broken conductor or missing return can interrupt the current path. A poor joint can instead act as an unwanted resistance.',check:'With the supply isolated, I inspect terminals, cable damage and polarity, then check the fuse, circuit continuity and physical enable/interlock wiring.',evidence:'An open path, incorrect pin or loose termination supports this hypothesis. If continuity looks normal, a controlled voltage-drop test under load can expose a resistive joint.',action:'I correct the identified connection, secure the harness and terminals, then repeat a controlled start.'},
{title:'The installed supply cannot support starting',why:'Longer or undersized cables, connector resistance and battery internal resistance can reduce controller input voltage under high starting current. Undervoltage or current protection may then prevent startup.',check:'I record battery terminal voltage and controller input voltage during the same controlled start, then compare current and protection indicators with equipment ratings.',evidence:'Battery voltage sag suggests the supply; a large difference between battery and controller points to cable or connection loss. A controller fault gives additional evidence, not a complete diagnosis by itself.',action:'I address the measured cause: battery condition, cable sizing, termination quality or protection configuration.'},
{title:'The drivetrain needs too much starting torque',why:'On the bench the motor may have little load. Installed, it must drive the gearbox, axle and wheels. Binding, misalignment, excessive friction or an engaged brake can keep it stationary.',check:'With traction isolated and the vehicle secured, I inspect brakes, alignment and drivetrain freedom. My investigation includes a controlled uncoupled comparison where the test arrangement supports it.',evidence:'A stiff drivetrain or successful uncoupled start supports a mechanical-load explanation. High current alone is not proof: it can also arise from electrical faults or other conditions.',action:'I work with the mechanical team to resolve binding or misalignment and compare starting torque demand with motor/controller capability.'}
];
function selectFault(i){const f=faults[i];$('#fault-panel').innerHTML=`<div class="faultlayout"><div><span class="number">0${i+1}</span><h3>${f.title}</h3><p>${f.why}</p></div><div class="teststeps"><div><b>Check</b><p>${f.check}</p></div><div><b>Evidence to look for</b><p>${f.evidence}</p></div><div><b>Response</b><p>${f.action}</p></div></div></div>`;$$('[data-fault]').forEach(b=>{let on=Number(b.dataset.fault)===i;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});}
$$('[data-fault]').forEach(b=>{b.addEventListener('click',()=>selectFault(Number(b.dataset.fault)));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?2:(Number(b.dataset.fault)+(e.key==='ArrowRight'?1:2))%3;selectFault(n);$$('[data-fault]')[n].focus()}})});selectFault(0);
function calculate(){let v=Number($('#voltage').value),i=Number($('#current').value),r=Number($('#resistance').value),drop=i*r,available=v-drop;$('#v-label').textContent=v+' V';$('#i-label').textContent=i+' A';$('#r-label').textContent=r.toFixed(3)+' Ω';$('#available').textContent=available.toFixed(1)+' V';$('#drop').textContent=drop.toFixed(1)+' V';$('#heat').textContent=(i*i*r).toFixed(0)+' W';$('#voltage-bar').style.width=Math.max(0,available/v*100)+'%';$('#lab-message').textContent=available<0?'These assumed values imply a negative controller input voltage: the fixed-current assumption is physically inconsistent here. Real current would change or protection would operate.':`At these illustrative values, ${Math.round(drop/v*100)}% of the battery terminal voltage is lost in the external wiring. Whether startup succeeds depends on the controller limits and mechanical load.`;}
$$('.controls input').forEach(i=>i.addEventListener('input',calculate));$('#reset-lab').onclick=()=>{$('#voltage').value=48;$('#current').value=80;$('#resistance').value=.05;calculate()};calculate();
const nodes={
battery:['Battery','The battery supplies DC energy. In my floating-supply proposal, the terminals are insulated from the chassis and any accessible conductive enclosure joins the bonding network. Battery operating voltage and starting capability inform component ratings.'],
protection:['DC fuse, isolator and contactor','I include a DC-rated fuse for overcurrent protection, an isolator for servicing and a contactor controlled by the safety chain. Voltage rating, interrupting capacity and fault-current coordination inform selection. Insulation faults are addressed by the monitoring and shutdown path.'],
controller:['Motor controller','The controller regulates power delivered to the motor. I propose compact switching loops, local decoupling, suitable EMI filtering and a bonded conductive enclosure. The control method remains a design input; PWM is a common implementation.'],
motor:['DC motor and drivetrain','The motor converts electrical power into torque through the gearbox, axle and wheels. I keep its paired conductors close together to reduce loop area, bond the metal casing and evaluate starting demand with the mechanical team.'],
aux:['Filtered auxiliary supply','I use a separately protected DC/DC branch to supply the communication PCB at its required voltage. The branch includes dedicated supply and return conductors, filtering and local decoupling to reduce conducted noise.'],
pcb:['Communication PCB','My proposal combines a bonded conductive enclosure, local decoupling and supply/port protection to reduce interference susceptibility. Logic reference, protective bonding and cable shield connections serve distinct functions in the grounding design.'],
cable:['Communication cable','I propose shielded twisted pair with a compatible differential interface, routed separately from traction power. Shield connections are made at enclosure entries, with signal termination matched to the selected communication protocol.'],
monitor:['Insulation monitoring','I monitor insulation between the floating DC conductors and bonded chassis. A detected fault reports to the safety chain, which removes contactor enable. Monitoring thresholds, response timing and shutdown scope are design inputs for verification.']
};
function selectNode(n){let d=nodes[n.dataset.node];$$('.node').forEach(x=>x.classList.toggle('active',x===n));}
$$('.node').forEach(n=>{n.addEventListener('click',()=>selectNode(n));n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n)}})});
$$('[data-layer]').forEach(b=>b.onclick=()=>{$$('[data-layer]').forEach(x=>x.setAttribute('aria-pressed',x===b));$$('.layer').forEach(g=>g.classList.toggle('dim',b.dataset.layer!=='all'&&!g.classList.contains(b.dataset.layer)))});
$('#download-diagram').onclick=()=>{let clone=$('#circuit').cloneNode(true);clone.querySelectorAll('.dim').forEach(n=>n.classList.remove('dim'));const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.svgheading{fill:#eef5fc;font:600 17px sans-serif}.svgsmall{fill:#b6c7d8;font:14px sans-serif}.center{text-anchor:middle}.powerline{fill:none;stroke:#ffb547;stroke-width:4}.return{stroke-dasharray:9 5}.bondline{fill:none;stroke:#62dfb6;stroke-width:3}.signalline{fill:none;stroke:#79baff;stroke-width:3;stroke-dasharray:7 4}.sense{fill:none;stroke:#79baff;stroke-width:2;stroke-dasharray:3 5}.node rect{fill:#1b2c3e;stroke:#577084;stroke-width:1.5;rx:5}.node>text:not(.svgsmall){fill:#eef5fc;text-anchor:middle;font:600 15px sans-serif}';clone.prepend(style);let url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='Wallaby-proposed-traction-diagram.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const emc={route:['Spatial coupling','Separating data and traction routes reduces close parallel field coupling.'],loop:['Radiated emissions','Closely paired supply and return conductors reduce current loop area.'],filter:['Conducted supply noise','Filtering and local decoupling reduce noise reaching the PCB through its supply.'],shield:['Cable susceptibility','A compatible twisted-pair interface and engineered shield termination reduce cable susceptibility.']};
function updateEMC(){let chosen=$$('[data-emc]:checked');$('#emc-status').textContent=chosen.length?`${chosen.length} of 4 control families considered`:'Coupling paths untreated';$('#emc-text').textContent=chosen.length?chosen.map(x=>emc[x.dataset.emc][1]).join(' ')+' I evaluate these controls through communication measurements during representative traction operation.':'';$('#emc-chips').innerHTML=chosen.map(x=>`<span class="chip">${emc[x.dataset.emc][0]}</span>`).join('')};$$('[data-emc]').forEach(x=>x.onchange=updateEMC);
let printState=[];window.addEventListener('beforeprint',()=>{printState=$$('details').map(d=>d.open);$$('details').forEach(d=>d.open=true)});window.addEventListener('afterprint',()=>{$$('details').forEach((d,i)=>d.open=printState[i])});$('#print').onclick=()=>window.print();
